/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Appointment': { kind: 'OBJECT'; name: 'Appointment'; fields: { 'endDateTime': { name: 'endDateTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'isException': { name: 'isException'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'note': { name: 'note'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'patient': { name: 'patient'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Patient'; ofType: null; }; } }; 'recurrenceId': { name: 'recurrenceId'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'recurrenceRule': { name: 'recurrenceRule'; type: { kind: 'OBJECT'; name: 'RecurrenceRule'; ofType: null; } }; 'startDateTime': { name: 'startDateTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'AppointmentsResult': { kind: 'OBJECT'; name: 'AppointmentsResult'; fields: { 'appointments': { name: 'appointments'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; }; }; }; } }; 'total': { name: 'total'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Boolean': unknown;
    'ByDay': { kind: 'OBJECT'; name: 'ByDay'; fields: { 'day': { name: 'day'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'Weekday'; ofType: null; }; } }; 'ordinal': { name: 'ordinal'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'ByDayInput': { kind: 'INPUT_OBJECT'; name: 'ByDayInput'; isOneOf: false; inputFields: [{ name: 'ordinal'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'day'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'Weekday'; ofType: null; }; }; defaultValue: null }]; };
    'CreateExceptionAppointmentInput': { kind: 'INPUT_OBJECT'; name: 'CreateExceptionAppointmentInput'; isOneOf: false; inputFields: [{ name: 'ruleId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'originalStartDateTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'newStartDateTime'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'newEndDateTime'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'note'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'CreateOneTimeAppointmentInput': { kind: 'INPUT_OBJECT'; name: 'CreateOneTimeAppointmentInput'; isOneOf: false; inputFields: [{ name: 'patientId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'startDateTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'endDateTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'note'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'CreatePatientInput': { kind: 'INPUT_OBJECT'; name: 'CreatePatientInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'dateOfBirth'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'phone'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'email'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'address'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'medicalHistory'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'CreateRecurrenceRuleInput': { kind: 'INPUT_OBJECT'; name: 'CreateRecurrenceRuleInput'; isOneOf: false; inputFields: [{ name: 'patientId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'frequency'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'RecurrenceFrequency'; ofType: null; }; }; defaultValue: null }, { name: 'interval'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'startDateTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'until'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'count'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'byDay'; type: { kind: 'LIST'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'ByDayInput'; ofType: null; }; }; defaultValue: null }, { name: 'byMonthDay'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'byMonth'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'byHour'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'byMinute'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'weekStart'; type: { kind: 'ENUM'; name: 'Weekday'; ofType: null; }; defaultValue: null }, { name: 'note'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'CreateWorkflowInput': { kind: 'INPUT_OBJECT'; name: 'CreateWorkflowInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'steps'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'WorkflowStepInput'; ofType: null; }; }; }; }; defaultValue: null }]; };
    'DeleteResult': { kind: 'OBJECT'; name: 'DeleteResult'; fields: { 'message': { name: 'message'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'success': { name: 'success'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'Float': unknown;
    'ID': unknown;
    'Int': unknown;
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'createExceptionForRule': { name: 'createExceptionForRule'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; }; } }; 'createOneTimeAppointment': { name: 'createOneTimeAppointment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; }; } }; 'createPatient': { name: 'createPatient'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Patient'; ofType: null; }; } }; 'createRecurrenceRule': { name: 'createRecurrenceRule'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RecurrenceRule'; ofType: null; }; } }; 'createWorkflow': { name: 'createWorkflow'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Workflow'; ofType: null; }; } }; 'deleteAppointment': { name: 'deleteAppointment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeleteResult'; ofType: null; }; } }; 'deletePatient': { name: 'deletePatient'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeleteResult'; ofType: null; }; } }; 'deleteRecurrenceRule': { name: 'deleteRecurrenceRule'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeleteResult'; ofType: null; }; } }; 'deleteWorkflow': { name: 'deleteWorkflow'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeleteResult'; ofType: null; }; } }; 'updatePatient': { name: 'updatePatient'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Patient'; ofType: null; }; } }; 'updateRecurrenceRule': { name: 'updateRecurrenceRule'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RecurrenceRule'; ofType: null; }; } }; 'updateWorkflow': { name: 'updateWorkflow'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Workflow'; ofType: null; }; } }; }; };
    'Patient': { kind: 'OBJECT'; name: 'Patient'; fields: { 'address': { name: 'address'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'appointments': { name: 'appointments'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; }; }; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'email': { name: 'email'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'insuranceInfo': { name: 'insuranceInfo'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'lastVisit': { name: 'lastVisit'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'medicalHistory': { name: 'medicalHistory'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'nextAppointment': { name: 'nextAppointment'; type: { kind: 'OBJECT'; name: 'Appointment'; ofType: null; } }; 'outstandingBalance': { name: 'outstandingBalance'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'phone': { name: 'phone'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'recurrenceRules': { name: 'recurrenceRules'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RecurrenceRule'; ofType: null; }; }; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'PatientsResult': { kind: 'OBJECT'; name: 'PatientsResult'; fields: { 'patients': { name: 'patients'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Patient'; ofType: null; }; }; }; } }; 'total': { name: 'total'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'allAppointments': { name: 'allAppointments'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AppointmentsResult'; ofType: null; }; } }; 'allPatients': { name: 'allPatients'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PatientsResult'; ofType: null; }; } }; 'allWorkflows': { name: 'allWorkflows'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'WorkflowsResult'; ofType: null; }; } }; 'appointmentsByPatient': { name: 'appointmentsByPatient'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AppointmentsResult'; ofType: null; }; } }; 'currentUser': { name: 'currentUser'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; 'patient': { name: 'patient'; type: { kind: 'OBJECT'; name: 'Patient'; ofType: null; } }; 'workflow': { name: 'workflow'; type: { kind: 'OBJECT'; name: 'Workflow'; ofType: null; } }; }; };
    'RecurrenceFrequency': { name: 'RecurrenceFrequency'; enumValues: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY'; };
    'RecurrenceRule': { kind: 'OBJECT'; name: 'RecurrenceRule'; fields: { 'byDay': { name: 'byDay'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'ByDay'; ofType: null; }; } }; 'byHour': { name: 'byHour'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'byMinute': { name: 'byMinute'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'byMonth': { name: 'byMonth'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'byMonthDay': { name: 'byMonthDay'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'count': { name: 'count'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'frequency': { name: 'frequency'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'RecurrenceFrequency'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'interval': { name: 'interval'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'note': { name: 'note'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'patient': { name: 'patient'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Patient'; ofType: null; }; } }; 'rruleString': { name: 'rruleString'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'startDateTime': { name: 'startDateTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'until': { name: 'until'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'weekStart': { name: 'weekStart'; type: { kind: 'ENUM'; name: 'Weekday'; ofType: null; } }; }; };
    'String': unknown;
    'UpdatePatientInput': { kind: 'INPUT_OBJECT'; name: 'UpdatePatientInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'dateOfBirth'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'phone'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'email'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'address'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'medicalHistory'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'UpdateRecurrenceRuleInput': { kind: 'INPUT_OBJECT'; name: 'UpdateRecurrenceRuleInput'; isOneOf: false; inputFields: [{ name: 'frequency'; type: { kind: 'ENUM'; name: 'RecurrenceFrequency'; ofType: null; }; defaultValue: null }, { name: 'interval'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'startDateTime'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'until'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'count'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'byDay'; type: { kind: 'LIST'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'ByDayInput'; ofType: null; }; }; defaultValue: null }, { name: 'byMonthDay'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'byMonth'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'byHour'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'byMinute'; type: { kind: 'LIST'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'weekStart'; type: { kind: 'ENUM'; name: 'Weekday'; ofType: null; }; defaultValue: null }, { name: 'note'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'UpdateWorkflowInput': { kind: 'INPUT_OBJECT'; name: 'UpdateWorkflowInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'steps'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'WorkflowStepInput'; ofType: null; }; }; }; defaultValue: null }]; };
    'User': { kind: 'OBJECT'; name: 'User'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'role': { name: 'role'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'UserRole'; ofType: null; }; } }; }; };
    'UserRole': { name: 'UserRole'; enumValues: 'ADMIN' | 'DOCTOR' | 'STAFF'; };
    'Weekday': { name: 'Weekday'; enumValues: 'SU' | 'MO' | 'TU' | 'WE' | 'TH' | 'FR' | 'SA'; };
    'Workflow': { kind: 'OBJECT'; name: 'Workflow'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'steps': { name: 'steps'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'WorkflowStep'; ofType: null; }; }; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'WorkflowStep': { kind: 'OBJECT'; name: 'WorkflowStep'; fields: { 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'order': { name: 'order'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'WorkflowStepInput': { kind: 'INPUT_OBJECT'; name: 'WorkflowStepInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'order'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }]; };
    'WorkflowsResult': { kind: 'OBJECT'; name: 'WorkflowsResult'; fields: { 'total': { name: 'total'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'workflows': { name: 'workflows'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Workflow'; ofType: null; }; }; }; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}